;;; Copyright (c) 2003-2013 uim Project https://github.com/uim/uim
;;;
;;; All rights reserved.
;;;
;;; Redistribution and use in source and binary forms, with or without
;;; modification, are permitted provided that the following conditions
;;; are met:
;;; 1. Redistributions of source code must retain the above copyright
;;;    notice, this list of conditions and the following disclaimer.
;;; 2. Redistributions in binary form must reproduce the above copyright
;;;    notice, this list of conditions and the following disclaimer in the
;;;    documentation and/or other materials provided with the distribution.
;;; 3. Neither the name of authors nor the names of its contributors
;;;    may be used to endorse or promote products derived from this software
;;;    without specific prior written permission.
;;;
;;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND
;;; ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;;; IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;;; ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE
;;; FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;;; DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
;;; OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
;;; HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
;;; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
;;; OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
;;; SUCH DAMAGE.
;;;

(require-extension (unittest))

(define lst #f)

(define (setup)
  (set! lst '(1 "2" three (4) 5 six "7" (8 8) -9)))

(test-begin "truncate-list")
(setup)
(test-equal '()
            (truncate-list () 0))
(test-false (truncate-list () 1))
(test-equal '()
            (truncate-list '("foo" "bar" "baz") 0))
(test-equal '("foo")
            (truncate-list '("foo" "bar" "baz") 1))
(test-equal '("foo" "bar")
            (truncate-list '("foo" "bar" "baz") 2))
(test-equal '("foo" "bar" "baz")
            (truncate-list '("foo" "bar" "baz") 3))
(test-false (truncate-list '("foo" "bar" "baz") 4))
(test-end)

(test-begin "proc-or")
(setup)
(test-false (proc-or))
(test-false (proc-or #f))
(test-eq #t (proc-or #t))
(test-false (proc-or #f #f))
(test-eq #t (proc-or #f #t))
(test-eq #t (proc-or #t #f))
(test-eq #t (proc-or #t #t))
(test-false (proc-or #f #f #f))
(test-eq #t (proc-or #f #f #t))
(test-eq #t (proc-or #f #t #f))
(test-eq #t (proc-or #f #t #t))
(test-eq #t (proc-or #t #f #f))
(test-eq #t (proc-or #t #f #t))
(test-eq #t (proc-or #t #t #f))
(test-eq #t (proc-or #t #t #t))
(test-false (apply proc-or ()))
(test-false (apply proc-or '(#f)))
(test-eq #t (apply proc-or '(#t)))
(test-false (apply proc-or '(#f #f)))
(test-eq #t (apply proc-or '(#f #t)))
(test-eq #t (apply proc-or '(#t #f)))
(test-eq #t (apply proc-or '(#t #t)))
(test-false (apply proc-or '(#f #f #f)))
(test-eq #t (apply proc-or '(#f #f #t)))
(test-eq #t (apply proc-or '(#f #t #f)))
(test-eq #t (apply proc-or '(#f #t #t)))
(test-eq #t (apply proc-or '(#t #f #f)))
(test-eq #t (apply proc-or '(#t #f #t)))
(test-eq #t (apply proc-or '(#t #t #f)))
(test-eq #t (apply proc-or '(#t #t #t)))
(test-end)

(test-begin "proc-and")
(setup)
(test-eq #t (proc-and))
(test-false (proc-and #f))
(test-eq #t (proc-and #t))
(test-false (proc-and #f #f))
(test-false (proc-and #f #t))
(test-false (proc-and #t #f))
(test-eq #t (proc-and #t #t))
(test-false (proc-and #f #f #f))
(test-false (proc-and #f #f #t))
(test-false (proc-and #f #t #f))
(test-false (proc-and #f #t #t))
(test-false (proc-and #t #f #f))
(test-false (proc-and #t #f #t))
(test-false (proc-and #t #t #f))
(test-eq #t (proc-and #t #t #t))
(test-eq #t (apply proc-and ()))
(test-false (apply proc-and '(#f)))
(test-eq #t (apply proc-and '(#t)))
(test-false (apply proc-and '(#f #f)))
(test-false (apply proc-and '(#f #t)))
(test-false (apply proc-and '(#t #f)))
(test-eq #t (apply proc-and '(#t #t)))
(test-false (apply proc-and '(#f #f #f)))
(test-false (apply proc-and '(#f #f #t)))
(test-false (apply proc-and '(#f #t #f)))
(test-false (apply proc-and '(#f #t #t)))
(test-false (apply proc-and '(#t #f #f)))
(test-false (apply proc-and '(#t #f #t)))
(test-false (apply proc-and '(#t #t #f)))
(test-eq #t (apply proc-and '(#t #t #t)))
(test-end)

;; See "Specification changes of utility procedures" of doc/COMPATIBILITY
(test-begin "sublist-uim-1.5")
(setup)
;; 0
(test-equal '()
            (sublist lst 0 0))
(test-equal '(1)
            (sublist lst 0 1))
(test-equal '(1 "2")
            (sublist lst 0 2))
(test-equal '(1 "2" three)
            (sublist lst 0 3))
(test-equal '(1 "2" three (4))
            (sublist lst 0 4))
(test-equal '(1 "2" three (4) 5 six "7")
            (sublist lst 0 7))
(test-equal '(1 "2" three (4) 5 six "7" (8 8))
            (sublist lst 0 8))
(test-equal '(1 "2" three (4) 5 six "7" (8 8) -9)
            (sublist lst 0 9))
(test-error (sublist lst 0 10))
;; 1
(test-error (sublist lst 1 0))
(test-equal '()
            (sublist lst 1 1))
(test-equal '("2")
            (sublist lst 1 2))
(test-equal '("2" three)
            (sublist lst 1 3))
(test-equal '("2" three (4))
            (sublist lst 1 4))
(test-equal '("2" three (4) 5 six "7")
            (sublist lst 1 7))
(test-equal '("2" three (4) 5 six "7" (8 8))
            (sublist lst 1 8))
(test-equal '("2" three (4) 5 six "7" (8 8) -9)
            (sublist lst 1 9))
(test-error (sublist lst 1 10))
;; 2
(test-error (sublist lst 2 0))
(test-error (sublist lst 2 1))
(test-equal '()
            (sublist lst 2 2))
(test-equal '(three)
            (sublist lst 2 3))
(test-equal '(three (4))
            (sublist lst 2 4))
(test-equal '(three (4) 5 six "7")
            (sublist lst 2 7))
(test-equal '(three (4) 5 six "7" (8 8))
            (sublist lst 2 8))
(test-equal '(three (4) 5 six "7" (8 8) -9)
            (sublist lst 2 9))
(test-error (sublist lst 2 10))
;; 3
(test-error (sublist lst 3 0))
(test-error (sublist lst 3 1))
(test-error (sublist lst 3 2))
(test-equal '()
            (sublist lst 3 3))
(test-equal '((4))
            (sublist lst 3 4))
(test-equal '((4) 5)
            (sublist lst 3 5))
(test-equal '((4) 5 six "7" (8 8))
            (sublist lst 3 8))
(test-equal '((4) 5 six "7" (8 8) -9)
            (sublist lst 3 9))
(test-error (sublist lst 3 10))
;; 8
(test-error (sublist lst 8 0))
(test-error (sublist lst 8 1))
(test-error (sublist lst 8 2))
(test-error (sublist lst 8 3))
(test-error (sublist lst 8 4))
(test-error (sublist lst 8 7))
(test-equal '()
            (sublist lst 8 8))
(test-equal '(-9)
            (sublist lst 8 9))
(test-error (sublist lst 8 10))
;; 9
(test-error (sublist lst 9 0))
(test-error (sublist lst 9 1))
(test-error (sublist lst 9 2))
(test-error (sublist lst 9 3))
(test-error (sublist lst 9 4))
(test-error (sublist lst 9 7))
(test-error (sublist lst 9 8))
(test-equal '()
            (sublist lst 9 9))
(test-error (sublist lst 9 10))
(test-end)

(test-begin "sublist-rel-uim-1.5")
(setup)
;; 0
(test-error (sublist-rel lst 0 -1))
(test-equal '()
            (sublist-rel lst 0 0))
(test-equal '(1)
            (sublist-rel lst 0 1))
(test-equal '(1 "2")
            (sublist-rel lst 0 2))
(test-equal '(1 "2" three)
            (sublist-rel lst 0 3))
(test-equal '(1 "2" three (4))
            (sublist-rel lst 0 4))
(test-equal '(1 "2" three (4) 5)
            (sublist-rel lst 0 5))
(test-equal '(1 "2" three (4) 5 six "7" (8 8))
            (sublist-rel lst 0 8))
(test-equal '(1 "2" three (4) 5 six "7" (8 8) -9)
            (sublist-rel lst 0 9))
(test-error (sublist-rel lst 0 10))
;; 1
(test-error (sublist-rel lst 1 -1))
(test-equal '()
            (sublist-rel lst 1 0))
(test-equal '("2")
            (sublist-rel lst 1 1))
(test-equal '("2" three)
            (sublist-rel lst 1 2))
(test-equal '("2" three (4))
            (sublist-rel lst 1 3))
(test-equal '("2" three (4) 5)
            (sublist-rel lst 1 4))
(test-equal '("2" three (4) 5 six)
            (sublist-rel lst 1 5))
(test-equal '("2" three (4) 5 six "7" (8 8) -9)
            (sublist-rel lst 1 8))
(test-error (sublist-rel lst 1 9))
(test-error (sublist-rel lst 1 10))
;; 2
(test-error (sublist-rel lst 2 -1))
(test-equal '()
            (sublist-rel lst 2 0))
(test-equal '(three)
            (sublist-rel lst 2 1))
(test-equal '(three (4))
            (sublist-rel lst 2 2))
(test-equal '(three (4) 5)
            (sublist-rel lst 2 3))
(test-equal '(three (4) 5 six)
            (sublist-rel lst 2 4))
(test-equal '(three (4) 5 six "7")
            (sublist-rel lst 2 5))
(test-equal '(three (4) 5 six "7" (8 8) -9)
            (sublist-rel lst 2 7))
(test-error (sublist-rel lst 2 8))
(test-error (sublist-rel lst 2 9))
(test-error (sublist-rel lst 2 10))
;; 3
(test-error (sublist-rel lst 3 -1))
(test-equal '()
            (sublist-rel lst 3 0))
(test-equal '((4))
            (sublist-rel lst 3 1))
(test-equal '((4) 5)
            (sublist-rel lst 3 2))
(test-equal '((4) 5 six)
            (sublist-rel lst 3 3))
(test-equal '((4) 5 six "7")
            (sublist-rel lst 3 4))
(test-equal '((4) 5 six "7" (8 8))
            (sublist-rel lst 3 5))
(test-equal '((4) 5 six "7" (8 8) -9)
            (sublist-rel lst 3 6))
(test-error (sublist-rel lst 3 7))
(test-error (sublist-rel lst 3 8))
(test-error (sublist-rel lst 3 9))
;; 8
(test-error (sublist-rel lst 8 -1))
(test-equal '()
            (sublist-rel lst 8 0))
(test-equal '(-9)
            (sublist-rel lst 8 1))
(test-error (sublist-rel lst 8 2))
(test-error (sublist-rel lst 8 3))
(test-error (sublist-rel lst 8 4))
(test-error (sublist-rel lst 8 5))
(test-error (sublist-rel lst 8 6))
(test-error (sublist-rel lst 8 7))
(test-error (sublist-rel lst 8 8))
(test-error (sublist-rel lst 8 9))
;; 9
(test-error (sublist-rel lst 9 -1))
(test-equal '()
            (sublist-rel lst 9 0))
(test-error (sublist-rel lst 9 1))
(test-error (sublist-rel lst 9 2))
(test-error (sublist-rel lst 9 3))
(test-error (sublist-rel lst 9 4))
(test-error (sublist-rel lst 9 5))
(test-error (sublist-rel lst 9 6))
(test-error (sublist-rel lst 9 7))
(test-error (sublist-rel lst 9 8))
(test-error (sublist-rel lst 9 9))
(test-end)

(test-begin "list-head")
(setup)
(test-equal '()
            (list-head lst 0))
(test-equal '(1)
            (list-head lst 1))
(test-equal '(1 "2")
            (list-head lst 2))
(test-equal '(1 "2" three)
            (list-head lst 3))
(test-equal '(1 "2" three (4) 5 six "7" (8 8))
            (list-head lst 8))
(test-equal '(1 "2" three (4) 5 six "7" (8 8) -9)
            (list-head lst 9))
(test-error (list-head lst 10))
(test-error (list-head lst -1))
(test-end)

(test-begin "alist-replace")
(setup)
(define alist '())
(set! alist (alist-replace '(first 1 "1") alist))
(test-equal '((first 1 "1"))
            alist)
(set! alist (alist-replace '(second 2 "2") alist))
(test-equal '((second 2 "2") (first 1 "1"))
            alist)
(set! alist (alist-replace '(third 3 "3") alist))
(test-equal '((third 3 "3") (second 2 "2") (first 1 "1"))
            alist)
(set! alist (alist-replace '(second two "two") alist))
(test-equal '((third 3 "3") (second two "two") (first 1 "1"))
            alist)
(test-end)

(test-begin "list-join")
(setup)
(test-equal '()
            (list-join () ()))
(test-equal '(())
            (list-join '(()) ()))
(test-equal '(1)
            (list-join '(1) ()))
(test-equal '(() () ())
            (list-join '(() ()) ()))
(test-equal '(1 () 2)
            (list-join '(1 2) ()))
(test-equal '(1 () 2 () 3)
            (list-join '(1 2 3) ()))
(test-equal '(one () two () three)
            (list-join '(one two three) ()))
(test-equal '("1" () "2" () "3")
            (list-join '("1" "2" "3") ()))
(test-equal '(() () () () ())
            (list-join '(() () ()) ()))
(test-equal '()
            (list-join () "/"))
(test-equal '(())
            (list-join '(()) "/"))
(test-equal '(1)
            (list-join '(1) "/"))
(test-equal '(() "/" ())
            (list-join '(() ()) "/"))
(test-equal '(1 "/" 2)
            (list-join '(1 2) "/"))
(test-equal '(1 "/" 2 "/" 3)
            (list-join '(1 2 3) "/"))
(test-equal '(one "/" two "/" three)
            (list-join '(one two three) "/"))
(test-equal '("1" "/" "2" "/" "3")
            (list-join '("1" "2" "3") "/"))
(test-equal '(() "/" () "/" ())
            (list-join '(() () ()) "/"))
(test-end)

(test-begin "nthcdr")
(setup)
(set! lst '(1 2 3 4))
(test-equal '(1 2 3 4)
            (nthcdr 0 lst))
(test-equal '(2 3 4)
            (nthcdr 1 lst))
(test-equal '(3 4)
            (nthcdr 2 lst))
(test-equal '(4)
            (nthcdr 3 lst))
(test-equal '()
            (nthcdr 4 lst))
(test-equal #f
            (nthcdr 5 lst))
(test-end)

(test-report-result)
