;;; Copyright (c) 2003-2013 uim Project https://github.com/uim/uim
;;;
;;; All rights reserved.
;;;
;;; Redistribution and use in source and binary forms, with or without
;;; modification, are permitted provided that the following conditions
;;; are met:
;;; 1. Redistributions of source code must retain the above copyright
;;;    notice, this list of conditions and the following disclaimer.
;;; 2. Redistributions in binary form must reproduce the above copyright
;;;    notice, this list of conditions and the following disclaimer in the
;;;    documentation and/or other materials provided with the distribution.
;;; 3. Neither the name of authors nor the names of its contributors
;;;    may be used to endorse or promote products derived from this software
;;;    without specific prior written permission.
;;;
;;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND
;;; ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;;; IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;;; ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE
;;; FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;;; DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
;;; OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
;;; HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
;;; LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
;;; OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
;;; SUCH DAMAGE.
;;;

(require-extension (unittest))

(define lst '(1 "2" three (4) 5 six "7" (8 8) -9))
(define lst2 '(1 "2" three (4) 5 six "7" (8 8) -9 #f 11 #f "13"))
(define lst3 '("1" "2" "three"))
(define lst4 '(1 2 3))
(define lst5 '(1 #f 3 "four"))
(define lst6 '(#f #f))
(define lst7 '(#f #f #f))
(define alist-int '((23 "23" twentythree)
                    (1 "1" one)
                    (5 "5" five)
                    (3 "3" three)))
(define alist-str '(("23" 23 twentythree)
                    ("1" 1 one)
                    ("5" 5 five)
                    ("3" 3 three)))
(define alist-lst '((("23") 23 twentythree)
                    (("1") 1 one)
                    (("5") 5 five)
                    (("3") 3 three)))
(define alist-sym '((twentythree "23" 23)
                    (one "1" 1)
                    (five "5" 5)
                    (three "3" 3)))

(test-begin "list-tabulate")
(test-equal '()
            (list-tabulate 0 (lambda (x) x)))
(test-equal '(0)
            (list-tabulate 1 (lambda (x) x)))
(test-equal '(0 1 2 3 4)
            (list-tabulate 5 (lambda (x) x)))
(test-equal '(0 1 4 9 16)
            (list-tabulate 5 (lambda (x) (* x x))))
(test-error (list-tabulate -1 (lambda (x) x)))
(test-end)

(test-begin "make-list")
(test-equal '(fill fill fill)
            (make-list 3 'fill))
(test-equal '(0 0 0)
            (make-list 3 0))
(test-equal '("string" "string" "string")
            (make-list 3 "string"))
(test-equal '((fill "fill") (fill "fill") (fill "fill"))
            (make-list 3 '(fill "fill")))
(test-equal '(() () ())
            (make-list 3 ()))
(test-equal '(())
            (make-list 1 ()))
(test-equal '()
            (make-list 0 ()))
(test-equal '()
            (make-list 0 'fill))
(test-error (make-list -1 'fill))
(test-end)

(test-begin "iota")
(test-equal '()
            (iota 0))
(test-equal '(0)
            (iota 1))
(test-equal '(0 1 2 3 4)
            (iota 5))
(test-error (iota -1))
(test-equal '()
            (iota 0 0))
(test-equal '(0)
            (iota 1 0))
(test-equal '(0 1 2 3 4)
            (iota 5 0))
(test-error (iota -1 0))
(test-equal '()
            (iota 0 1))
(test-equal '(1)
            (iota 1 1))
(test-equal '(1 2 3 4 5)
            (iota 5 1))
(test-error (iota -1 1))
(test-equal '(3)
            (iota 1 3))
(test-equal '(3 4 5 6 7)
            (iota 5 3))
(test-error (iota -1 3))
(test-equal '(5 6 7 8 9)
            (iota 5 5))
(test-end)

(test-begin "zip")
(test-equal '((1) (2) (3) (4) (5))
            (zip '(1 2 3 4 5)))
(test-equal '((1 "1" one) (2 "2" two) (3 "3" three)
              (4 "4" four) (5 "5" five))
            (zip '(1 2 3 4 5)
                  '("1" "2" "3" "4" "5")
                  '(one two three four five)))
(test-equal '((1 "1" one) (2 "2" two) (3 "3" three))
            (zip '(1 2 3 4 5)
                  '("1" "2" "3" "4" "5")
                  '(one two three)))
(test-equal '()
            (zip '()
                  '("1" "2" "3" "4" "5")
                  '(one two three)))
(test-equal '()
            (zip '()))
(test-end)

(test-begin "append-map")
(test-equal '()
            (append-map car '()))
(test-equal '(c)
            (append-map car '(((c) (C)))))
(test-equal '(c a)
            (append-map car '(((c) (C)) ((a) (A)))))
(test-equal '(c a r)
            (append-map car '(((c) (C)) ((a) (A)) ((r) (R)))))
(test-end)

(test-begin "append-reverse")
(test-equal '("5" "4" "3" "2" "1" six seven eight)
            (append-reverse '("1" "2" "3" "4" "5")
                             '(six seven eight)))
(test-equal '(six seven eight)
            (append-reverse '()
                            '(six seven eight)))
(test-equal '("5" "4" "3" "2" "1")
            (append-reverse '("1" "2" "3" "4" "5")
                            '()))
(test-equal '()
            (append-reverse '()
                            '()))
(test-end)

(test-begin "find")
(test-equal "2"
            (find string? lst))
(test-equal 'three
            (find symbol? lst))
(test-equal #f
            (find string? '()))
(test-equal -9
            (find (lambda (x)
                    (and (integer? x)
                         (< x 0)))
                  lst))
(test-end)

(test-begin "any")
(test-eq #t (any string? lst))
(test-eq #t (any string? lst2))
(test-eq #t (any string? lst3))
(test-false (any string? lst4))
(test-equal 1
            (any proc-or lst2))
(test-false (any proc-or lst6))
(test-equal 1
            (any proc-or lst2 lst6))
(test-equal 1
            (any proc-or lst6 lst2))
(test-false (any proc-or lst6 lst7))
(test-equal 1
            (any proc-or lst5 lst6 lst7))
(test-false (any string? '()))
(test-end)

(test-begin "every")
(test-false (every string? lst))
(test-false (every string? lst2))
(test-eq #t (every string? lst3))
(test-false (every string? lst4))
(test-equal (last lst)
            (every proc-or lst))
(test-false (every proc-or lst2))
(test-false (every proc-or lst6))
(test-equal "2"
            (every proc-or lst2 lst6))
(test-equal "2"
            (every proc-or lst6 lst2))
(test-false (every proc-or lst6 lst7))
(test-equal 2
            (every proc-or lst4 lst6 lst7))
(test-false (every proc-or lst5 lst6 lst7))
(test-eq #t (every string? '()))
(test-end)

(test-begin "fold")
(test-equal '()
            (fold cons '() '()))
(test-equal '(5 4 3 2 1)
            (fold cons '() '(1 2 3 4 5)))
(test-equal '(1 2 3 4 5 6 7 8 9)
            (fold cons '(6 7 8 9) '(5 4 3 2 1)))
(test-equal '(9 8 7 6 5 4 3 2 1)
            (fold cons '(5 4 3 2 1) '(6 7 8 9)))
(test-equal 24
            (fold + 0 '(1 2 3 4 5) '(1 2 1 2 3)))
(test-equal 9
            (fold + 0 '(1 2 3 4 5) '(1 2 1 2 3) '(7)))
(test-equal 0
            (fold + 0 '(1 2 3 4 5) '() '(1 2 1 2 3)))
(test-equal 120
            (fold * 1 '(1 2 3 4 5)))
(test-equal 14400
            (fold * 1 '(1 2 3 4 5) '(1 2 3 4 5)))
(test-end)

(test-begin "unfold")
;; immediate term
(test-equal '()
            (unfold (lambda (x)
                      (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5))
(test-equal '(5)
            (unfold (lambda (x)
                      (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5
                    (lambda (rest)
                      (list rest))))
(test-equal '(-1)
            (unfold (lambda (x)
                       (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5
                    (lambda (rest)
                      '(-1))))
;; 5 times
(test-equal '(5 4 3 2 1)
            (unfold (lambda (x)
                      (= x 0))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5))
(test-equal '(5 4 3 2 1 0)
            (unfold (lambda (x)
                       (= x 0))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5
                    (lambda (x)
                      (list x))))
(test-equal '(5 4 3 2 1 -1)
            (unfold (lambda (x)
                      (= x 0))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (- rest 1))
                    5
                    (lambda (x)
                      '(-1))))
;; 5 times, reversed
(test-equal '(0 1 2 3 4)
            (unfold (lambda (x)
                       (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (+ rest 1))
                     0))
(test-equal '(0 1 2 3 4 5)
            (unfold (lambda (x)
                      (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (+ rest 1))
                    0
                    (lambda (x)
                      (list x))))
(test-equal '(0 1 2 3 4 -1)
            (unfold (lambda (x)
                      (= x 5))
                    (lambda (rest)
                      rest)
                    (lambda (rest)
                      (+ rest 1))
                    0
                    (lambda (x)
                      '(-1))))
;; restruct same list
(test-equal '(0 1 2 3 4 5)
            (unfold null?
                    car
                    cdr
                    '(0 1 2 3 4 5)))
(test-equal '(0 1 2 3 4 5)
            (unfold null?
                    car
                    cdr
                    '(0 1 2 3 4 5)
                    (lambda (x)
                      x)))
(test-equal '(0 1 2 3 4 5 . -1)
            (unfold null?
                    car
                    cdr
                    '(0 1 2 3 4 5)
                    (lambda (x)
                      -1)))
(test-end)

(test-begin "filter")
(test-equal '()
            (filter not '()))
(test-equal '(5 6 4)
            (filter (lambda (x)
                      (< 3 x))
                    '(3 5 2 6 4 1)))
(test-equal '("2" "7")
            (filter string?
                    '(one "2" 3 #f (5) six "7" 8 (9) 10)))
(test-equal '(3 8 10)
            (filter integer?
                    '(one "2" 3 #f (5) six "7" 8 (9) 10)))
(test-end)

(test-begin "filter-map")
;; single list
(test-equal '()
            (filter-map not '()))
(test-equal '(5 6 4)
            (filter-map (lambda (x)
                          (and (< 3 x)
                               x))
                        '(3 5 2 6 4 1)))
(test-equal '(10 12 8)
            (filter-map (lambda (x)
                          (and (< 3 x)
                               (* 2 x)))
                        '(3 5 2 6 4 1)))
(test-equal '(#t #t)
            (filter-map string?
                        '(one "2" 3 #f (5) six "7" 8 (9) 10)))
(test-equal '(#t #t #t)
            (filter-map integer?
                        '(one "2" 3 #f (5) six "7" 8 (9) 10)))
;; multiple lists
(test-equal '()
            (filter-map +
                        '()
                        '()))
(test-equal '(8 11 10 8)
            (filter-map (lambda (x y)
                          (let ((sum (+ x y)))
                            (and (< 6 sum)
                                 sum)))
                        '(3 5 2 6 4 1)
                        '(1 3 9 4 2 7)))
(test-equal '()
            (filter-map (lambda (x y)
                          (let ((sum (+ x y)))
                            (and (< 6 sum)
                                 sum)))
                        '()
                        '(1 3 9 4 2 7)))
(test-equal '(8 11 10)
            (filter-map (lambda (x y)
                          (let ((sum (+ x y)))
                            (and (< 6 sum)
                                 sum)))
                        '(3 5 2 6 4 1)
                        '(1 3 9 4)))
(test-equal '("aAa1" "bBb2" "cCc3" "dDd4")
            (filter-map string-append
                        '("a" "b" "c" "d")
                        '("A" "B" "C" "D")
                        '("a" "b" "c" "d")
                        '("1" "2" "3" "4" "5")))
(test-end)

(test-begin "remove")
(test-equal '(1 three (4) 5 six (8 8) -9)
            (remove string? lst))
(test-equal '("2" three (4) six "7" (8 8))
            (remove integer? lst))
(test-equal '("2" three (4) six "7" (8 8) -9)
            (remove (lambda (x)
                      (and (integer? x)
                           (> x 0)))
                    lst))
(test-equal '()
            (remove string? '()))
(test-equal '()
            (remove string? '("1" "2")))
(test-end)

(test-begin "alist-delete")
(test-equal '((23 "23" twentythree)
              (1 "1" one)
              (5 "5" five))
            (alist-delete 3 alist-int))
(test-equal '((23 "23" twentythree)
              (1 "1" one)
              (5 "5" five)
              (3 "3" three))
            (alist-delete 0 alist-int))
(test-equal '((1 "1" one)
              (5 "5" five)
              (3 "3" three))
            (alist-delete 23 alist-int))
(test-equal '((23 "23" twentythree)
              (1 "1" one)
              (5 "5" five)
              (3 "3" three))
            (alist-delete "3" alist-int))
(test-equal '(("23" 23 twentythree)
              ("1" 1 one)
              ("3" 3 three))
            (alist-delete "5" alist-str))
(test-error (alist-delete "5" alist-str =))
(test-equal '(("23" 23 twentythree)
              ("1" 1 one)
              ("5" 5 five)
              ("3" 3 three))
            (alist-delete "5" alist-str eqv?))
(test-equal '(("23" 23 twentythree)
              ("1" 1 one)
              ("3" 3 three))
            (alist-delete "5" alist-str string=?))
(test-equal '((("1") 1 one)
              (("5") 5 five)
              (("3") 3 three))
            (alist-delete '("23") alist-lst))
(test-equal '((("1") 1 one)
              (("5") 5 five)
              (("3") 3 three))
            (alist-delete '("23") alist-lst equal?))
(test-equal '((twentythree "23" 23)
              (five "5" 5)
              (three "3" 3))
            (alist-delete 'one alist-sym))
(test-equal '((twentythree "23" 23)
              (one "1" 1)
              (five "5" 5))
            (alist-delete 'three alist-sym eq?))
(test-end)

(test-report-result)
